# Generated by Django 3.1 on 2021-04-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_saving_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('URL', models.URLField(max_length=100)),
                ('Phone_Number', models.IntegerField()),
            ],
        ),
    ]
