# Generated by Django 3.1 on 2021-04-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_saving_db',
            name='Phone_Number',
            field=models.IntegerField(max_length=10),
        ),
    ]
